apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-awxr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-awxr
    app.kubernetes.io/part-of: load-app-12fff2eb-1f38-4dc8-bcae-b8ba3e2ed67a
  name: devfile-sample-awxr
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-awxr
status:
  loadBalancer: {}
